#!/bin/bash

#Fail this script should any operation fail
set -e
set -o pipefail

#Global App Configuration
declare APPNAME="nouncaptcha";
declare APPUSER="${APPNAME}"
declare APPDB="${APPNAME}"
declare RUNFILE="run";
declare PROD_RUNFILE="runprod"

function enforce_root {
    if [ "$(whoami)" != "root" ];
    then
        echo "Please re-run this script as root (eg: 'sudo bash deploy')";
        exit;
    fi
}

function user_exists {
    if [ -n "$(getent passwd $1)" ];
    then
        return 0 #true
    fi
    return 1 #false
}

function db_exists {
    if [ `builtin type -p psql` ];
    then
        if sudo -u postgres psql $1 -c '' 2>/dev/null;
        then
            return 0; #true
        fi
    fi
    return 1; #false
}

function display_uninstall_warnings {
    if user_exists $APPUSER;
    then
        echo "The user named \"${APPUSER}\" (and their home dir) will be deleted! (type 'continue' to continue, any other input will exit)"
        read input
        if [ "${input}" != "continue" ];
        then
            exit;
        fi
    fi

    if db_exists $APPDB;
    then 
        echo "The database named \"${APPDB}\" will be dropped! (type 'continue' to continue, any other input will exit)"
        read input
        if [ "${input}" != "continue" ];
        then
            exit;
        fi
    fi
}

# Takes one optional argument, $DISABLE_UNINSTALL_WARNINGS
# If true, uninstall will skip any blocking warnings. Otherwise, the checks are run.
function uninstall {
    if !($1)
    then
        display_uninstall_warnings
    fi

    echo "####Deleting the App's User (${APPUSER}) and their home directory####"
    echo "############################################################"
    if [ -n "$(getent passwd $APPUSER)" ]
    then
        userdel -r ${APPUSER}
    else
        echo "The app's user could not be found"
    fi

    echo "##########Dropping any ${APPDB} postgres data##########"
    echo "############################################################"
    if [ `builtin type -p psql` ];
    then
        echo "DROP DATABASE ${APPDB}; DROP USER ${APPUSER};" | sudo -u postgres psql
    else
        echo "Postgres does not appear to be installed"
    fi

    echo "##########Removing any installed node libraries##########"
    echo "############################################################"
    if [ -d node_modules ];
    then
        rm -rf node_modules
    else
        echo "No node modules installed, nothing removed"
    fi

    echo "##########Removing runfile (${RUNFILE})##########"
    echo "############################################################"
    if [ -f ${RUNFILE} ];
    then
        rm -f ${RUNFILE}
    else
        echo "No runfile found, nothing removed"
    fi

    echo "##########Removing prod runfile (${PROD_RUNFILE})##########"
    echo "############################################################"
    if [ -f ${PROD_RUNFILE} ];
    then
        rm -f ${PROD_RUNFILE}
    else
        echo "No prod runfile found, nothing removed"
    fi
}

function install_app_packages {
    echo "##########Installing node libraries##########"
    echo "############################################################"
    su $SUDO_USER -c "npm install"
    npm install -g forever
}

# Takes one optional argument, $PORT
# If set, $PORT specifies the preferred port to run the nodejs HTTP server on (default 4000)
function configure_app {
    #File names
    declare APPEXE="server.js"; #The point of entry for the app
    #Port config
    declare PORT_VARNAME="NOUNCAPTCHA_PORT";
    declare -i PORT=4000;
    #DB config
    declare PASSWORD="$(cat /dev/urandom | tr -dc '[:alnum:]' | head -c 32)"; #Generate a strong alphanumeric password from random input
    declare DB_URL_VARNAME="NOUNCAPTCHA_DB_URL";
    declare DB_URL="postgres://nouncaptcha:${PASSWORD}@localhost:5432/nouncaptcha";
    declare DB_FILE="db_stuff/basic_database.dump";

    if [ "$1" -ne 0 ];
    then
        PORT=$1;
    fi

    echo "##########Proactively checking for potential issues##########"
    echo "############################################################"
    if user_exists $APPUSER;
    then
        echo "The app's runtime context, a user named \"${APPUSER}\", already exists, the install script will not work!";
        exit;
    fi
    if db_exists $APPDB;
    then 
        echo "A database named \"${APPDB}\" already exists, the install script will not work!";
        exit;
    fi

    echo "##########Creating the App's User Context (${APPUSER})##########"
    echo "############################################################"
    useradd ${APPUSER}
    echo ${APPUSER}:${PASSWORD} | chpasswd
    mkhomedir_helper ${APPUSER}
    su - ${APPUSER} -c ""

    echo "##########Configuring Postgres##########"
    echo "############################################################"
    sudo -u postgres createuser ${APPUSER} --no-createdb --no-createrole --no-superuser
    sudo -u postgres createdb $APPDB
    echo "ALTER USER ${APPUSER} WITH PASSWORD '${PASSWORD}'" | sudo -u postgres psql $APPDB
    echo "REVOKE CONNECT ON DATABASE ${APPDB} FROM PUBLIC; GRANT CONNECT ON DATABASE ${APPDB} TO ${APPUSER};" | sudo -u postgres psql $APPDB
    sudo -u postgres psql $APPDB < $DB_FILE
    echo "GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO ${APPUSER};" | sudo -u postgres psql $APPDB

    echo "##########Creating the app's runfile (${RUNFILE})##########"
    echo "############################################################"
    #Overwrite anything in ${RUNFILE}, or create it.
    echo "#!/bin/bash
    export ${PORT_VARNAME}=${PORT};
    export ${DB_URL_VARNAME}=\"${DB_URL}\";
    declare FOREVER_ARGS=\"-w\";
    while getopts 'p:sh' option
    do
        case \$option in
            p ) export ${PORT_VARNAME}=\${OPTARG}; ;;
            s ) FOREVER_ARGS=\"\${FOREVER_ARGS} -s\"; ;;
            h ) echo \"Help (-h): See readme.md for script arguments and other info.\"; exit; ;;
        esac
    done
    eval \"./node_modules/forever/bin/forever \${FOREVER_ARGS} ${APPEXE}\"
    " > ${RUNFILE}
    chown $SUDO_USER ${RUNFILE}

    echo "##########Creating the app's production runfile (${PROD_RUNFILE})##########"
    echo "############################################################"
    #Overwrite anything in ${PROD_RUNFILE}, or create it.
    declare PWD=$(pwd);
    echo "#!/bin/bash" > ${PROD_RUNFILE}
    echo "screen -dmS ${APPNAME} bash -c \"sudo su ${APPUSER} -c 'export NODE_ENV=production; cd ${PWD} && bash ${RUNFILE};'\"" >> ${PROD_RUNFILE};
    chown $SUDO_USER ${PROD_RUNFILE}
}

#Script command-line options
declare RUN_INSTALL=false;
declare -i PORT_ARG=0;
declare RUN_UNINSTALL=false;
declare DISABLE_UNINSTALL_WARNINGS=false;

while getopts 'ip:uzh' option
do
    case $option in
        i ) RUN_INSTALL=true; ;;
        p ) PORT_ARG=${OPTARG}; ;;
        u ) RUN_UNINSTALL=true; ;;
        z ) DISABLE_UNINSTALL_WARNINGS=true; ;;
        h ) echo "Help (-h): See readme.md for script arguments and other info."; exit; ;;
    esac
done

enforce_root;

if $RUN_UNINSTALL
then
    uninstall $DISABLE_UNINSTALL_WARNINGS; 
fi

if $RUN_INSTALL
then
    install_app_packages;
    configure_app $PORT_ARG; 
fi
